spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE} # name을 지정을 안하면 배치프로그램의 모든 job들이 실행된다

---

spring:
  config:
    activate: # profile이 local일때 activate한다.
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house # 데이터베이스 스키마명: house
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  batch:
    jdbc:
      initialize-schema: ALWAYS # 매번 스키마를 초기화 한다.

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2
